dist: trusty
language: rust
services: docker
sudo: required

rust: nightly

env: TARGET=thumbv6m-none-eabi

before_install: set -e

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
